# Generated by Django 3.1.8 on 2021-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
