# Generated by Django 3.1.8 on 2021-06-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_prescription_authorize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='complete',
        ),
    ]
