# Generated by Django 3.1.8 on 2021-06-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_prescription_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
