# Generated by Django 3.1.8 on 2021-06-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_prescription_authorize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='authorize',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
